Lesson18(final)
JuicyFlash/test-guru pull request #17
Opened 2022-10-31 22:58 UTC by JuicyFlash

Реализовано задание бейджи

2022-11-01 07:29 UTC, VidgarVii requested changes

2022-11-01 07:29 UTC, VidgarVii commented on app/controllers/admin/badges_controller.rb
> +  end
`def edit; end`

2022-11-01 07:29 UTC, VidgarVii commented on app/controllers/admin/badges_controller.rb
> +end
в конце файла надо отставлять 1 пустую строчку. Это указатель на конец файла. Сейчас система думает, что происходит обрыв файла. Даже гитхаб ругается. No new lina at end of file. Многие компиляторы тут выдадут ошибку. Руби частично компилируемый язык. И такой разрыв легко проглотит. Но в реальных проектах это как красная тряпка для быка. Так что тренируем дисциплину и больше такого не совершаем! В руби за чистоту кода!

2022-11-01 07:29 UTC, VidgarVii commented on app/controllers/given_badges_controller.rb
> +end
код должен быть единообразен. Используй рубокоп. К этому уроку таких стилистических ошибок уже не должно быть
```
class GivenBadgesController < ApplicationController
  def index
    @badges = current_user.badges
  end
end
```

2022-11-01 07:29 UTC, VidgarVii commented on app/controllers/processed_tests_controller.rb
> +    @badges = BadgeService.new(@processed_test).call
в данном решении можно постоянно обновлять данную страницу результата и получать баджи. Либо нагружать систему. 
Бадж следует выдавать после завершения теста. А он завершается не тут

2022-11-01 07:29 UTC, VidgarVii commented on app/helpers/badges_helper.rb
> +      #  "Edit #{test.title} Test"
отладочный код надо удалять
Если это документация, то её пишут выше метода

2022-11-01 07:29 UTC, VidgarVii commented on app/helpers/badges_helper.rb
> +    end
end уехал веред

2022-11-01 07:29 UTC, VidgarVii commented on app/javascript/utilities/badges/rule_description.js
> +    var rule_type =  document.querySelectorAll('#badge_rule_type')[0]
Время глобальных var-ов прошло. при объявлении переменных используй let/const. Так безопасней и код становиться понятней. Обязательно по гугли отличие!

2022-11-01 07:29 UTC, VidgarVii commented on app/models/badge.rb
> +
лишние отступы. Будь внимательней! Вроде бы меточь, а на работу с таким кодом уже не возьмут(. Там за каждый пробел будут ругать

2022-11-01 07:29 UTC, VidgarVii commented on app/services/badge_service.rb
> +  def initialize(processed_test)
перед константой и методом надо оставлять пустую строку

2022-11-01 07:29 UTC, VidgarVii commented on app/services/badge_service.rb
> +           finish_tests_by_level:FinishTestsByLevelRuleSpecification,
неоченьприятночитатьтакойкод

2022-11-01 07:29 UTC, VidgarVii commented on app/views/admin/badges/_form.html.erb
> +          <%= form.collection_select :rule_type, BadgeService.rules, :first, :last, id: :rule_type, prompt:  t('helpers.select.badge.prompt'), class: 'form-select'  %>
как хранилище статичных данных используют константы. Хорошо бы такую константу определить в модели бадж. По смыслу очень подходит

2022-11-01 07:29 UTC, VidgarVii commented on app/services/badge_service.rb
> +  end
процедурный стиль можно заменить одним методом map
map вернёт изменённый массив 
each_with_object для каких то преоброзований

2022-11-01 07:29 UTC, VidgarVii commented on app/services/finish_any_test_by_first_try_rule_specification.rb
> +    "За успешное прохождение теста с первого раза"
1 контекст всегда хранят в файлах локализации
2 Так же используя файл локализации делает этот метод не нужным. По типу правила можно получать нужный контекст
3 Спецификации ни когда не хранят какие-то данные или описание. Он только решает вопрос удовлетворённости

2022-11-01 07:29 UTC, VidgarVii commented on app/services/finish_any_test_by_first_try_rule_specification.rb
> +       ProcessedTest.where("user_id=? and test_id=? and id<>?", @processed_test.user_id, @processed_test.test_id, @processed_test.id).empty?
ну почему такой бардак с отступами?(
Не можешь следить сам за этим ни чего страшного, используй рубоком! Ну чтобы был везде порядок!

2022-11-01 07:29 UTC, VidgarVii commented on app/services/finish_tests_by_category_rule_specification.rb
> +    category = Category.where(title:@value).first
если ты используешь не `id`, а `title`, то логично будет добавить валидацию уникальности этого поля в модели `Category`
по этому такие проверки лучше делать по "ай-ди" (в большинстве случаев)

2022-11-01 07:29 UTC, VidgarVii commented on app/services/finish_tests_by_category_rule_specification.rb
> +  end
разбей это большой сложный не читаемый код на маленькие простые методы с понятными названиями

2022-11-01 07:29 UTC, VidgarVii commented on app/services/badge_service.rb
> +    Badge.all.each do |badge|
лучше используй find_each для итераций.
метод .all почти не используют. Так как если в БД окажется большое кол-во данных, то данный метод полностью заполнит оперативную память.  И сервер зависнет

2022-11-01 07:29 UTC, VidgarVii commented on app/services/badge_service.rb
> +    if (@processed_test.user.badges.where("badge_id=?", badge.id).empty? && badge.unique) || !badge.unique
везде где возможно читаемей и безопасней использовать хеш синтаксис
`.where(badge_id: badge.id)`

2022-11-01 07:29 UTC, VidgarVii commented on app/services/badge_service.rb
> +      @processed_test.user.badges << badge
в каждой итерации происходит запрос в базу на вставку баджа.
На много эффективней было бы это делать 1 раз.
Сначала получаешь список заработанных баджей, А затем их добавляешь юзеру

2022-11-09 07:25 UTC, BubuntuClu requested changes

2022-11-09 07:25 UTC, BubuntuClu commented on app/services/finish_any_test_by_first_try_rule_specification.rb
> +      ProcessedTest.where('user_id=? and test_id=? and id<>?', @processed_test.user_id, @processed_test.test_id,
если используешь методы активрекорда, то используй синтаксис который больше подходит актив рекорду `whre(user_id: @processed_test.user_id, ...)`
если надо вставить кусок чистого sql подключай `Arel`

2022-11-09 07:25 UTC, BubuntuClu commented on app/services/finish_any_test_by_first_try_rule_specification.rb
> +    if @processed_test.success?
`return false unless @processed_test.success?`
чтобы не оборачивать весь код в `if/else` выражение

2022-11-09 07:25 UTC, BubuntuClu commented on app/services/finish_tests_by_category_rule_specification.rb
> +    Category.where(title: category_name).first
чтобы не исопльзовать `first` используй `find_by`

2022-11-09 07:25 UTC, BubuntuClu commented on app/services/finish_tests_by_category_rule_specification.rb
> +  def successful_user_tests_ids_by_category(category_id)
почему такой сложный код полуачется? тебе надо сравнить массив тестов категории и массив тестов категории, которые прошел пользователь. что за обработки массивов ты делаешь?
тут же все должно быть два запроса и сравнение между ними результатов

2022-11-09 07:25 UTC, BubuntuClu commented on app/services/finish_tests_by_level_rule_specification.rb
> +  def successful_user_tests_ids_by_level(level)
тут тоже самое что и в категориях. должно быть два запроса и сравнение их результатов. никаких рубишных обработок не должно быть. максимально фильтруй данные на этапе запроса к БД

2022-11-09 07:25 UTC, BubuntuClu commented on app/services/finish_any_test_by_first_try_rule_specification.rb
> +      ProcessedTest.where('user_id=? and test_id=? and id<>?', @processed_test.user_id, @processed_test.test_id,
кстати, этот запрос вообще будет правильно работать? ты прошел этот тест, в каком случае ты тут получишь `true`?

2022-11-10 06:48 UTC, BubuntuClu commented on app/services/finish_tests_by_category_rule_specification.rb
> +    ready_tests_ids == user_processed_tests_by_category(category.id).select(&:success?).pluck(:test_id).uniq
`select(&:success?)` это рубишная обработка результатов. чтобы ее не было добавь новое поле в таблицу и выставляй его в `true`когда тест пройден успешно. таким образом ты просто через фильтрацию по полю получишь нужный список, вместо обхода всех тестов и подсчетов результатов у них

2022-11-10 17:19 UTC, BubuntuClu commented on app/services/finish_tests_by_category_rule_specification.rb
> +    ready_tests_ids = ready_tests_ids_by_category(category.id)
это еще можно упростить. у тебя в модели тестов есть метод, который делает поиск тестов по названию категории, вот сюда он идеально вписывается

2022-11-10 19:26 UTC, merged