Lesson8
JuicyFlash/test-guru pull request #7
Opened 2022-03-25 19:02 UTC by JuicyFlash

Реализованы стандартные действия и представления для ресурса вопросов
Реализовано представление для ресурса тестов (с количеством вопросов по каждому тесту)
Добавлен футер по заданию
Добавлены хелперы по заданию

2022-03-26 18:04 UTC, BubuntuClu requested changes

2022-03-26 18:04 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    question = find_question
почему это не через колбэк сделано?

2022-03-26 18:04 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +      render :new
тут рендерить надо редактирование

2022-03-26 18:04 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    redirect_to test_questions_path
стоит указать редирект на тест удаленного вопроса

2022-03-26 18:04 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  before_action :find_test, only: %i[index create new edit]
зачем тест нужен для редиктирования?

2022-03-26 18:04 UTC, BubuntuClu commented on app/helpers/questions_helper.rb
> +  def question_header(action)
передавай сюда объект вопроса и по его состоянияю определяй какой метод использовать

2022-03-26 18:04 UTC, BubuntuClu commented on app/views/questions/edit.html.erb
> +<h1><%= question_header(:edit) %></h1>
после переделки метода, эта строка тоже перейдет в форму

2022-03-26 18:04 UTC, BubuntuClu commented on app/views/tests/index.html.erb
> +  <% Test.all.each do |test| %>
в коде экшена получай список вопроса, не стоит выносить запросы во вьюху

2022-03-26 18:04 UTC, BubuntuClu commented on config/routes.rb
> +    resources :questions#, shallow: true
надо вернуть опцию

2022-03-26 18:04 UTC, BubuntuClu commented on app/views/questions/index.html.erb
> +<h1><%= @test.title %></h1>
эта вьюху и метод в контроллере не нужен. отображение вопросов переехать должно в tests#show

2022-03-28 15:18 UTC, JuicyFlash commented
1. Список тестов - tests#index
2. Детализация теста (тест + список вопросов) - tests#show, рендерится с помощью фрагмента questions\_index (не уверен в что корректно называть так фрагмент)
3. Фрагмент для рендеринга списка вопросов questions\_index.html.erb
4. Routes shallow: true
5. В хелпер question_header теперь передаётся объект question

2022-03-28 16:49 UTC, BubuntuClu requested changes

2022-03-28 16:49 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +  before_action :find_test, only: %i[show]
не стоит делать колбэки ради одного экшена. ты написал гораздо больше кода чтобы найти тест, когда можно написать одну строку прямо в экшене

2022-03-28 16:49 UTC, BubuntuClu commented on app/views/layouts/application.html.erb
> +  <footer> <%= current_year %>
это стоит вынести в паршиал `_footer`

2022-03-28 16:49 UTC, BubuntuClu commented on app/views/questions/_index.html.erb
>  <table>
лучше не делать такой паршиал. можно использовать `render @test.questions`, но тогда должен быть паршиал `_question`

2022-03-28 16:49 UTC, BubuntuClu commented on app/views/questions/_form.erb
> +<%= form_with url: resource_path, model: @question, local: true do |form| %>
`Для того чтобы метод form_with смог сформировать верный URL используйте вызов form_with model: [@parent, @child]` используй `form_with model`, чтобы роут строился сам, не надо параметром прокидывать его в форму

2022-03-28 17:38 UTC, JuicyFlash commented
TestsController - убрал колбэки и лишние методы
Добавлен фрагмент _footer
Добавлен фрагмен _question + рендеринг @test.questions в tests#show
Фрагмент _form - убрал проброс пути через параметр, перешёл на form_with model: [@parent, @child]

2022-03-29 21:54 UTC, merged